### ISSUE TITLE
Show racks names in 3D view

### ISSUE THREAD

**Issue by mehdid** [edf-hpc/slurm-web#80]

**Comment by robink** [comment]
Au dessus du rack en mode panneau avec une largeur, quelque chose de soft

**Comment by rezib** [comment]
The introduction of file `js/fonts/helvetiker_regular.typeface.js` is not great... It must considered as a _binary_ file w/o source file.

We must either find a way to:

* build from its source file at build time,
* avoid using it.

**Comment by Aenohe** [comment]
Fixed

**Comment by rezib** [comment]
For this issue, we just expect a nodejs command to build the `*.typeface.js` file from a source font file in order to generate it at build time.

**Comment by rezib** [comment]
Just developed a debian package for opentype.js, as requested:
https://github.com/edf-hpc/opentypejs

**Comment by rezib** [comment]
My bad, re-opened because still missing the command to build the font.

**Comment by rezib** [comment]
There is a license issue with helvetiker font which seems to be a proprietary font indeed. The font must be removed from git repo.

Also, it would be better all the hard-coded references to the font could be removed in the code, as I'm seeing this currently:

```
js/modules/3d-view/iframe.js:    helvetiker: '../../../js/fonts/helvetiker_regular.typeface',
js/modules/3d-view/iframe.js:    helvetiker: {
js/modules/3d-view/iframe.js:      exports: 'helvetiker',
js/draw/3d-draw.js:  'helvetiker'
js/draw/3d-draw.js:          font: 'helvetiker',
```

I think a good option is to use dejavu fonts from this debian package:
https://packages.debian.org/jessie/fonts-dejavu-core

This way, we can remove font from slurm-web git repository and directly use those provided by this package.

**Comment by rezib** [comment]
According to @Aenohe it's possible to drop font path in dashboard conf. That's definitely what must be done, it would be perfect then!

**Comment by rezib** [comment]
We're still expecting the following things:

* remove the current proprietary font from git repository
* remove all hard-coded references to _helvetiker_ in the source code
* add configuration parameter to set path to the typeface font file in dashboard configuration

**Comment by rezib** [comment]
We converted standard open source font DejaVuSans with your script from https://github.com/derniercri/font4three and opentype.js 0.4.3, using this command:

```
nodejs /usr/lib/nodejs/font-converter.js /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf > js/fonts/DejaVuSans.typeface.js
```

But when we try to use it, no rack show up and we get this error in firefox development console:

```
SyntaxError: unterminated string literal DejaVuSans.typeface.js:2:988413
uncaught exception: The font DejaVu Sans with normal weight and normal style is missing.
```

The original TTF file can be found in this package: https://packages.debian.org/jessie/fonts-dejavu-core
The resulting typeface font is: [DejaVuSans.typeface.js.zip](https://github.com/edf-hpc/slurm-web/files/284641/DejaVuSans.typeface.js.zip)

How to fix this?

**Comment by Lorel** [comment]
the font `DejaVu Sans Mono` works, try this one

**Comment by rezib** [comment]
It's finally OK with DejaVu Sans Mono.
